/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfazjuegoaz;

import Entidades.Juego;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.DefaultListModel;
import javax.swing.Timer;


/**
 *
 * @author Usuario
 */
public class PantallaJugadores extends javax.swing.JFrame {

    private Juego juego;

    private void setLista() {
        DefaultListModel<String> jugadores = new DefaultListModel<>();
        for (String jugador : this.juego.listaJugadores) {
            jugadores.addElement(jugador);
        }
        this.jListJugadores.setModel(jugadores);
    }
    
    private void removeJugador(){
        String remueveme = this.jListJugadores.getSelectedValue();
        this.juego.listaJugadores.remove(remueveme);
        setLista();
    }
    
    private void limpiarFormulario() {
        jTxtNombre.setText("");
    }

    private boolean validarCampos() {
        String nombre = jTxtNombre.getText();
        if (nombre.length() < 3) {
            jLblExito.setText("Nombre más de 3 caracteres.");
            jLblExito.setForeground(Color.RED);
            ocultarMensaje();
            return false;
        }
        return true;
    }

    private String generarNombreUnico(String nombre) {
        String nombreUnico = nombre;
        int contador = 1;
        while (this.juego.listaJugadores.contains(nombreUnico)) {
            nombreUnico = nombre + "_" + contador;
            contador++;
        }
        return nombreUnico;
    }

    private void ocultarMensaje() {
        Timer timer = new Timer(3000, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                jLblExito.setText("");
            }
        });
        timer.setRepeats(false); // Para que el Timer solo se ejecute una vez
        timer.start();
    }

    /**
     * Creates new form PantallaFinal
     */
    public PantallaJugadores() {
        this.juego = Juego.getJuego();
        initComponents();
        setLista();
        setLocationRelativeTo(null);
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPnl0 = new javax.swing.JPanel();
        jLblFinal = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jListJugadores = new javax.swing.JList<>();
        jLblTurnoParticipante1 = new javax.swing.JLabel();
        jLblFinal1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel0 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTxtNombre = new javax.swing.JTextField();
        jBtnAgregar = new javax.swing.JButton();
        jBtnVolver = new javax.swing.JButton();
        jLblExito = new javax.swing.JLabel();
        jBtnQuitar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPnl0.setBackground(new java.awt.Color(204, 204, 255));

        jLblFinal.setFont(new java.awt.Font("Gill Sans Ultra Bold", 2, 36)); // NOI18N
        jLblFinal.setText("LISTADO");

        jListJugadores.setFont(new java.awt.Font("Gill Sans Ultra Bold", 0, 18)); // NOI18N
        jListJugadores.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(jListJugadores);

        jLblTurnoParticipante1.setFont(new java.awt.Font("Gill Sans Ultra Bold", 2, 24)); // NOI18N
        jLblTurnoParticipante1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Logo.png"))); // NOI18N

        jLblFinal1.setFont(new java.awt.Font("Gill Sans Ultra Bold", 2, 36)); // NOI18N
        jLblFinal1.setText("DE JUGADORES ");

        jLabel1.setFont(new java.awt.Font("Showcard Gothic", 1, 36)); // NOI18N
        jLabel1.setText("Jugador");

        jLabel0.setFont(new java.awt.Font("Showcard Gothic", 1, 36)); // NOI18N
        jLabel0.setText("AGREGAR");

        jLabel2.setFont(new java.awt.Font("Gill Sans Ultra Bold", 2, 24)); // NOI18N
        jLabel2.setText("NOMBRE:   ");

        jTxtNombre.setFont(new java.awt.Font("Gill Sans Ultra Bold", 0, 24)); // NOI18N

        jBtnAgregar.setBackground(new java.awt.Color(255, 153, 102));
        jBtnAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/AGREGARBTN.png"))); // NOI18N
        jBtnAgregar.setContentAreaFilled(false);
        jBtnAgregar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBtnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAgregarActionPerformed(evt);
            }
        });

        jBtnVolver.setBackground(new java.awt.Color(255, 153, 102));
        jBtnVolver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/BTNREGRESAR.png"))); // NOI18N
        jBtnVolver.setContentAreaFilled(false);
        jBtnVolver.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBtnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnVolverActionPerformed(evt);
            }
        });

        jLblExito.setFont(new java.awt.Font("Sitka Banner", 0, 18)); // NOI18N
        jLblExito.setText("   ");
        jLblExito.setAlignmentX(0.5F);

        jBtnQuitar.setBackground(new java.awt.Color(255, 153, 102));
        jBtnQuitar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/btnQuitar.png"))); // NOI18N
        jBtnQuitar.setContentAreaFilled(false);
        jBtnQuitar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBtnQuitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnQuitarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPnl0Layout = new javax.swing.GroupLayout(jPnl0);
        jPnl0.setLayout(jPnl0Layout);
        jPnl0Layout.setHorizontalGroup(
            jPnl0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnl0Layout.createSequentialGroup()
                .addGroup(jPnl0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPnl0Layout.createSequentialGroup()
                        .addComponent(jBtnVolver)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLblTurnoParticipante1))
                    .addGroup(jPnl0Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPnl0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jTxtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPnl0Layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addGroup(jPnl0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jBtnAgregar)
                            .addGroup(jPnl0Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jBtnQuitar)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPnl0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLblFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLblFinal1, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPnl0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLblExito, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 349, Short.MAX_VALUE)))
                .addContainerGap(29, Short.MAX_VALUE))
            .addGroup(jPnl0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPnl0Layout.createSequentialGroup()
                    .addGap(22, 22, 22)
                    .addComponent(jLabel0)
                    .addContainerGap(522, Short.MAX_VALUE)))
        );
        jPnl0Layout.setVerticalGroup(
            jPnl0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnl0Layout.createSequentialGroup()
                .addGroup(jPnl0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLblTurnoParticipante1)
                    .addGroup(jPnl0Layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(jLblFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLblFinal1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLblExito, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jBtnVolver))
                .addGroup(jPnl0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPnl0Layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jTxtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jBtnAgregar))
                    .addGroup(jPnl0Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBtnQuitar)
                .addContainerGap(83, Short.MAX_VALUE))
            .addGroup(jPnl0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPnl0Layout.createSequentialGroup()
                    .addGap(197, 197, 197)
                    .addComponent(jLabel0, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(393, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPnl0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPnl0, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAgregarActionPerformed
        if (!validarCampos()) {
            limpiarFormulario();
            return;
        }

        String jugador = jTxtNombre.getText();
        jugador = generarNombreUnico(jugador);
        if (this.juego.listaJugadores.add(jugador)) {
            jLblExito.setText("Jugador añadido: " + jugador);
            jLblExito.setForeground(Color.BLACK);
            ocultarMensaje();
            limpiarFormulario();
            setLista();
            System.out.println(jugador);
        }
    }//GEN-LAST:event_jBtnAgregarActionPerformed

    private void jBtnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnVolverActionPerformed
        PantallaJuego pa = new PantallaJuego();
        pa.setVisible(true);
        dispose();
    }//GEN-LAST:event_jBtnVolverActionPerformed

    private void jBtnQuitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnQuitarActionPerformed
        removeJugador();
    }//GEN-LAST:event_jBtnQuitarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallaJugadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallaJugadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallaJugadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaJugadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PantallaJugadores().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnAgregar;
    private javax.swing.JButton jBtnQuitar;
    private javax.swing.JButton jBtnVolver;
    private javax.swing.JLabel jLabel0;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLblExito;
    private javax.swing.JLabel jLblFinal;
    private javax.swing.JLabel jLblFinal1;
    private javax.swing.JLabel jLblTurnoParticipante1;
    private javax.swing.JList<String> jListJugadores;
    private javax.swing.JPanel jPnl0;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTxtNombre;
    // End of variables declaration//GEN-END:variables
}
